### PR TITLE
fix issue #96 

### PR DESCRIPTION
**Pull request by sam2x**
Fixing #96

### CODE REVIEW

**Comment by maritz** [comment]
Can you add tests that fail without this fix and pass with the fix?

**Comment by sam2x** [comment]
@maritz updated PR. Thanks to the tests, i spotted that find method could be directly call, which resulted to a fail. From now, I will remember to use them each time before submitting a PR.
I added tests that check for my PR, it checks that findAndLoad returns properly Nohm objects (and not Ids when called without args).

**Comment by sam2x** [comment]
left a console.log,  i'm removing it.... git is such pain to deal with...

**Comment by sam2x** [comment]
done

**Comment by sam2x** [comment]
Example of test that fail (without patch) : 

findTests.js
✔ find - loadInvalid
✔ find - load
✔ find - findAndLoad
✖ find - findAndLoadAll

Assertion Message: The loaded user is not a nohm instance
AssertionError: false == true
    at Object.ok (/tmp/nohm/node_modules/nodeunit/lib/types.js:83:39)
    at obj.<anonymous> (/tmp/nohm/test/findTests.js:256:9)
    at /tmp/nohm/lib/retrieve.js:116:16
    at convertIdsToInt (/tmp/nohm/lib/retrieve.js:25:3)
    at Command.returnFunction [as callback] (/tmp/nohm/lib/retrieve.js:115:5)
    at normal_reply (/tmp/nohm/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/tmp/nohm/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.returnReply (/tmp/nohm/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/tmp/nohm/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/tmp/nohm/node_modules/redis/index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)

**Comment by maritz** [comment]
Yeah, the CI checks were indicating a test failure as well, that would have been my next point. ;-)

I'll look into this PR in more detail hopefully soon.

**Pull request merged**
