### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by KarinaBauer**
That's a typo or just my misunderstanding?

### CODE REVIEW

**Comment by maritz** [comment]
Definitely a typo! Thanks a lot.

**Comment by maritz** [comment]
One tiny thing: could you change the commit message to something like the following so the automatic versioning knows what to do with it?

 `docs: fix typo` 

I could also do it in merging but then I'd have to squash and overwrite your contribution - clearly not ideal.

**Comment by KarinaBauer** [comment]
Yep, i'll do it

**Comment by KarinaBauer** [comment]
https://github.com/maritz/nohm/pull/144

**Pull request closed without merging**
