### PR TITLE
Support for ioredis

### PR DESCRIPTION
**Pull request by thepipster**
Added support for ioredis, issue https://github.com/maritz/nohm/issues/120, by converting uppercase function names to lowercase and reducing connection detection strictness

### CODE REVIEW

**Comment by maritz** [comment]
Thank you very much for this PR!

A couple of questions/requests, since I never really looked into ioredis in depth:
 - does it not offer a .connected equivalent?
 - could you do a check for whether connected is undefined or boolean, if it's boolean do the check (old way) if it's undefined just go ahead (current PR way)
 - could you add a check for an env var (e.g. NOHM_TEST_IOREDIS="true") to run all tests with ioredis instead of node-redis? This is a bit more work and I totally understand if you don't want to do it. In that case I will add it, but it'll take some time. I would then [add it to travis.yml](https://docs.travis-ci.com/user/environment-variables/#defining-multiple-variables-per-item) so that it runs all tests once with node-redis and once with ioredis.

**Comment by maritz** [comment]
Also, .DS_Store is a macOS specific file, right? Should probably be added to .gitignore instead of adding it to the repo :-)

**Comment by thepipster** [comment]
Thanks, sorry for delay - I'll take a look.

**Comment by thepipster** [comment]
So I think ioredis has the equivalent; 

`(client.connected || client.status === 'connect')`

**Comment by thepipster** [comment]
I made those changes, but the tests are failing (I think) at deleteNonExistant - might need some help to debug...

**Comment by maritz** [comment]
One thing that could still be added, but is entirely optional and could also go into its own PR is ioredis support in extra/stress.js.

Documentation is also missing for now.

**Comment by thepipster** [comment]
Awesome, thanks!

**Pull request closed without merging**
