### PR TITLE
Ability to access the object's instance when validating

### PR DESCRIPTION
**Pull request by johngeorgewright**
With this request I've also:

- added a `.editorconfig` file to help contributors (like myself) to keep to your coding standards.
- added ability to test on a database that's password protected (using the variable `--redis-auth`)

### CODE REVIEW

**Comment by maritz** [comment]
Hm, for some reason pubsub tests failed on this PR in travis. I'm assume this is an issue with iojs 2.3.0 or something similar instead of your code, but I will have to manually do some testing.

**Comment by johngeorgewright** [comment]
Yeh. I was racking my brain over that one too. I'll install iojs and see what's going on.

**Comment by johngeorgewright** [comment]
This is the problem: https://github.com/maritz/nohm/blob/master/lib/pubsub.js#L49

That condition is false and therefore the callback never gets called. I'd recommend always using the callback, and passing an error back if there is one.

**Comment by maritz** [comment]
It should get called as a callback to redis.psubscribe here https://github.com/maritz/nohm/blob/master/lib/pubsub.js#L63

**Comment by johngeorgewright** [comment]
oh yeh. whoops.

So the problem is that the `redis.psubscribe` isn't calling the given callback. Weird. Change in the "redis" API perhaps?

**Comment by johngeorgewright** [comment]
Nope... there's been no changes since August last year.

**Comment by maritz** [comment]
I suspect a problem with iojs 2.3.0. Something non-backwards-compatible. But I have no way to test or debug this right now. Probably not until the weekend or maybe even the weekend after.

**Comment by johngeorgewright** [comment]
Doesn't work in v0.10 either.

**Comment by mlaco** [comment]
Please excuse me if I'm way off base, but the [node_redis readme](https://github.com/NodeRedis/node_redis/blob/e4da320a291951351a755297585d719409334b65/README.md#psubscribe-pattern-count) shows that the arguments for `psubscribe` are `pattern` and `count`; the latter is not a callback. Could this be the problem?

**Comment by maritz** [comment]
What you linked to is the event arguments.
The callback given to a .psubscribe() is called once the subscription is established.

**Comment by maritz** [comment]
Finally published in v0.9.8. Sorry for the delay.

**Pull request merged**
